# Copyright (c) 2025 Ekkodale GmbH. All rights reserved.
#
# This file is part of the gaeco platform system.
#
# Use of this file is governed by the terms of the license
# in LICENSE.md at the root of this repository.
# Unauthorized copying, modification, distribution, or use of this file,
# via any medium, is strictly prohibited except as expressly permitted
# under that license.

services:
  platformconfig-client:
    image: ${IMAGE_BASE_PATH}/platformconfig-client:${PLATFORMCONFIG_CLIENT_TAG}
    expose:
      - 80
    environment:
      VITE_MOUNT_PATH: ${MOUNT_ROUTE}
      VITE_GUIDELINE_API_URL: https://${GUIDELINE_SERVER_HOSTNAME}
      VITE_ONTOLOGY_API_URL: https://${ONTOLOGY_SERVER_HOSTNAME}
    networks:
      - gaeco-network
    labels:
      "app.mfe.id": "app-platformconfig"
      "app.mfe.displayName": "Platform Config"
      "app.mfe.description": "Platform Config Application"
      "app.mfe.iconPath": "/platform-config.svg"
      "app.mfe.entrypointPath": "/assets/remoteEntry.js"
      "app.mfe.exposedModule": "App"
      "app.mfe.route": "${MOUNT_ROUTE}"

networks:
  gaeco-network:
    name: ${ENVIRONMENT_NETWORK}
    external: true
